# Шрифт
font_family      Hasklug Nerd Font
bold_font        JetBrainsMono Nerd Font Mono Bold
font_size        11.0

# Прозрачность (как HUD Тони Старка)
background_opacity 0.88
background_blur 20

# Курсор (золотой, как репульсор)
# cursor #FFB300
cursor_trail 1
cursor_shape beam
cursor_blink_interval 0.5


# Отступы
window_padding_width 8
window_margin 22
# Скрыть рамку
hide_window_decorations no

# Картинки
allow_remote_control yes

# ═══ IRON MAN COLORS ═══

# Фон — тёмный костюм
# background #0D0D0D
# foreground #E0E0E0

# Выделение
# selection_background #B71C1C
# selection_foreground #FFFFFF

# URL
# url_color #29B6F6

# Вкладки
# active_tab_background #B71C1C
# active_tab_foreground #FFD600
# inactive_tab_background #1A1A1A
# inactive_tab_foreground #757575

# Рамка окна
# active_border_color #FFB300
# inactive_border_color #424242

# ═══ ЦВЕТОВАЯ ПАЛИТРА ═══

# Чёрный (тёмная броня)
# color0  #0D0D0D
# color8  #424242

# Красный (Iron Man Red)
# color1  #B71C1C
# color9  #FF1744

# Зелёный (Arc Reactor зелёный отблеск)
# color2  #4CAF50
# color10 #69F0AE

# Жёлтый/Золотой (Gold Titanium)
# color3  #FFB300
# color11 #FFD600

# Синий (Arc Reactor Blue)
# color4  #1565C0
# color12 #29B6F6

# Пурпурный (Infinity Stone)
# color5  #7B1FA2
# color13 #CE93D8

# Циан (HUD голограмма)
# color6  #00ACC1
# color14 #4DD0E1

# Белый (Stark Industries)
# color7  #BDBDBD
# color15 #F5F5F5

# Fish как оболочка
shell /usr/bin/fish


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
