color0 #29141b
color1 #f63072
color2 #f8548a
color3 #f65b3b
color4 #f6b83b
color5 #fa85ab
color6 #f99985
color7 #f3f2f2
color8 #756167
color9 #f63072
color10 #f8548a
color11 #f65b3b
color12 #f6b83b
color13 #fa85ab
color14 #f99985
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #29141b
background            #29141b
foreground            #f3f2f2
selection_foreground  #b6afb1
selection_background  #371b24
active_border_color   #f8548a
inactive_border_color #371b24
url_color             #f8548a

active_tab_foreground   #25181d
active_tab_background   #f8548a
inactive_tab_foreground #b6afb1
inactive_tab_background #371b24
cursor_trail_color      #b6afb1
