color0 #0c0e31
color1 #fd4663
color2 #676fe4
color3 #57b3db
color4 #d05bd7
color5 #9398ec
color6 #96d0e9
color7 #f2f2f3
color8 #5e6073
color9 #fd4663
color10 #676fe4
color11 #57b3db
color12 #d05bd7
color13 #9398ec
color14 #96d0e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0c0e31
background            #0c0e31
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #101342
active_border_color   #676fe4
inactive_border_color #101342
url_color             #676fe4

active_tab_foreground   #181925
active_tab_background   #676fe4
inactive_tab_foreground #afafb6
inactive_tab_background #101342
cursor_trail_color      #afafb6
