color0 #101c2d
color1 #fd4663
color2 #6799e4
color3 #685cd6
color4 #a366cc
color5 #93b6ec
color6 #9e96e9
color7 #f2f2f3
color8 #5f6774
color9 #fd4663
color10 #6799e4
color11 #685cd6
color12 #a366cc
color13 #93b6ec
color14 #9e96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #101c2d
background            #101c2d
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #15253c
active_border_color   #6799e4
inactive_border_color #15253c
url_color             #6799e4

active_tab_foreground   #050608
active_tab_background   #6799e4
inactive_tab_foreground #afb2b6
inactive_tab_background #15253c
cursor_trail_color      #afb2b6
